name: Push
on:
  push:
    branches:
      - main
      - develop

env:
  REPOSITORY: blog-prod
  IMAGE_TAG: latest
  AWS_REGION: us-east-1

jobs:
  pipeline:
    name: Pipeline for build, test and deploy this service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ env.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $REGISTRY/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }} .
          docker push $REGISTRY/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
